version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: market_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: market_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/market_db
      - JWT_SECRET=secret
    depends_on:
      - mongodb
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: market_frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=https://localhost:5000/api
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
  uploads_data:
