const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const helmet = require('helmet');
const https = require('https');
const fs = require('fs');
const path = require('path');

require('dotenv').config();

const app = express();
app.use(helmet());
app.use(helmet.crossOriginResourcePolicy({ policy: "cross-origin" })); // Allow serving images/files
app.use(cors());
app.use(express.json());

// Expose uploads directory statically for images
// [VULN] File Upload: X-Content-Type-Options 헤더 제거 → 브라우저가 .html 파일을 실행
app.use('/uploads', (req, res, next) => {
  res.removeHeader('X-Content-Type-Options');
  next();
}, express.static(path.join(__dirname, 'uploads')));

const authRoutes  = require('./routes/auth');
const boardRoutes = require('./routes/board');
const chatRoutes  = require('./routes/chat');
const reviewRoutes = require('./routes/review');
const reportRoutes = require('./routes/report');

app.use('/api/auth',   authRoutes);
app.use('/api/board',  boardRoutes);
app.use('/api/chat',   chatRoutes);
app.use('/api/reviews', reviewRoutes);
app.use('/api/reports', reportRoutes);

app.get('/health', (req, res) => res.send('OK'));

const PORT = process.env.PORT || 5000;
const MONGO_URI = process.env.MONGO_URI || 'mongodb://mongodb:27017/market_db';

mongoose.connect(MONGO_URI)
  .then(async () => {
    console.log('MongoDB Connected');
    const User = require('./models/User');
    const adminExists = await User.findOne({ userId: 'admin' });
    if (!adminExists) {
      await new User({ userId: 'admin', password: 'admin', role: 'Admin', securityAnswer: 'admin' }).save();
      console.log('Default Admin Account Created (admin / admin)');
    }
  })
  .catch(err => console.log(err));

// Load HTTPS certs generated by Dockerfile
const sslOptions = {
  key: fs.readFileSync(path.join(__dirname, 'certs', 'server.key')),
  cert: fs.readFileSync(path.join(__dirname, 'certs', 'server.cert'))
};

https.createServer(sslOptions, app).listen(PORT, () => {
    console.log(`HTTPS Server running on port ${PORT}`);
});
